// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using WorkingWithSqlServerImages.Models;
using static ConfigurationLibrary.Classes.ConfigurationHelper;
#nullable disable

namespace WorkingWithSqlServerImages.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public virtual DbSet<Pictures> Pictures1 { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConnectionString());

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.Pictures1Configuration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
