// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WorkingWithSqlServerImages.Models;

namespace WorkingWithSqlServerImages.Data.Configurations;

public partial class Pictures1Configuration : IEntityTypeConfiguration<Pictures>
{
    public void Configure(EntityTypeBuilder<Pictures> entity)
    {
            

        entity.Property(e => e.Id).ValueGeneratedOnAdd();

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Pictures> entity);
}